### ISSUE TITLE
The if statements in the case statements - line 232

### ISSUE THREAD

**Issue by rece212** [SmartHydro/SmartHydro#11]
So I saw now looking at the code that if it indicates the case is true : then does a if statement followed by an action ( that makes sence ) but the log message is the same as the else statements.  Is this ment to continue spamming the same thing ? Also where is it logging ? In the serial ? So once we do final deployment can this be removed ?

**Comment by rudderz243** [comment]
@rece212 it is set up that way so that if it gets the same condition multiple times in a row, it doesn't keep spamming digital writes to the pins, and just returns the message. it also does not log the message to serial, it sets a local variable (there is one for each prediction model), which can be polled by the app
